- inpeak/build.gradle
- inpeak/compose.yaml
- inpeak/src/main/resources/application.properties
- inpeak/src/main/resources/application.yml
> close #1
> 개발환경 초기 세팅 완료했습니다.
> chore: 개발 환경 초기 세팅(#1)

- inpeak/src/main/java/com/blooming/inpeak/common/base/AuditingFields.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorBuildFactory.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorCode.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorHandlingController.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorResponse.java
> close #3
> `common` 패키지에 AuditingFields와 예외 처리 관련 로직들을 추가하였습니다.
> feat: Auditing fields 및 Error build factory 생성(#3)

- inpeak/build.gradle
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/dto/request/AnswerSkipRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/AnswerStatus.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
> ex) close #6 
> 답변 엔티티, 컨트롤러, 레포, 서비스 생성 및 스킵하기 기능 추가
>
> feat/answer 답변 스킵 기능 추가

- inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
> feat: 멤버 entity 정의 (#5)

- inpeak/src/main/java/com/blooming/inpeak/answer/Member.java
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
> ex) close #11 
> answer 테스트 추가
>
> Feat/answer 테스트 추가

- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
close #27
- 이전 PR과 main의 conflict를 해결했습니다..
> fix: question - main conflict 해결 (#27)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #29
> 정답 리스트 조회 기능에 관한 서비스, 레포지토리 테스트 코드 작성
>
> feat: 정답 리스트 조회 테스트 작성 (#29)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/AnswerStatus.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CorrectAnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/IncorrectAnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
- 오답노트 테스트 추가
- 정답 조회 코드와 중복된 부분 리펙토링
> ex) close #31
> 오답 노트 기능 생성 후 정답 리스트 조회 코드와 겹치는 부분 리펙토링
>
> feat: 오답노트 기능 추가(#31)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CorrectAnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/IncorrectAnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/interview/controller/InterviewController.java
- inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/CalendarResponse.java
- inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
- inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
- inpeak/src/test/java/com/blooming/inpeak/interview/service/InterviewServiceTest.java
> ex) close #36
> 캘린더 조회 기능 추가 및 테스트 추가
>
> Feat/calendar 캘린더 기능 추가

- .github/workflows/inpeak-ci.yml
close #43
<br>
- main 브랜치에 push와 pull request가 발생할 때 ci 동작
> chore: ci 환경 구성 (#43)

- inpeak/gradle/wrapper/gradle-wrapper.properties
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/InterviewWithAnswersResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #47
> 캘린더 리턴 타입 수정
> 이에 따른 테스트 수정
> answer 서비스 테스트 통합 테스트로 변경
>
> Refactor/answer 캘린더 기능 수정 및 테스트 수정

- .github/workflows/inpeak-ci.yml
- inpeak/.gitignore
- inpeak/build.gradle
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerPresignedUrlResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerPresignedUrlService.java
- inpeak/src/main/java/com/blooming/inpeak/common/config/s3/S3Config.java
- inpeak/src/main/resources/application.yml
- close #50
- 녹화 영상 업로드를 위한 presigned URL을 발급합니다.
- github actions workflow에 aws 설정 파일을 추가했습니다.
> feat: Presigned URL 발급

- inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
- inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
close #59 
- try-catch 블록을 명시적 조건 검사로 대체
- Optional을 활용한 사용자 조회 로직 개선
- 테스트 코드를 BDDMockito 스타일로 전환
- [Mockito vs BDDMockito](https://velog.io/@lxxjn0/Mockito와-BDDMockito는-뭐가-다를까)
> refactor: 토큰 인증 필터 예외 처리 및 테스트 개선 (#59)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerPresignedUrlService.java
- close #63 
- presigned url 메타데이터 수정
- 허용 확장자 추가
- 만료 시간 변경(15분 -> 5분)
- 프론트엔드 요청에 맞춰 controller 파라미터 수정
>
> refactor: presigned url 메타데이터 수정 (#63)

- .github/workflows/inpeak-ci.yml
- inpeak/.gitignore
- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerCreateCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/Message.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerCreateRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/GPTRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/GPTResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/UserAnswerStatsRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/GPTService.java
- inpeak/src/main/java/com/blooming/inpeak/common/config/AI/GPTConfig.java
- inpeak/src/main/resources/application.yml
- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/UserAnswerStatsRepositoryTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #65 
> GPT API 연동 및 프롬프트 작성
> 레디스에 정답 여부 저장
>
> Feat/answer/ai GPT 답변 기능 추가

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #67
> 이해 여부 변경 기능 추가
>
> feat: 이해 여부 변경 기능 추가(#67)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #69
> 코멘트 작성 기능 추가
>
> feat: 코멘트 작성 기능 추가(#69)

- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
> ex) close #74
> junit 테스트를 assertJ로 통일
>
> refactor: 테스트 assertJ로 통일(#74)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerCreateCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerCreateRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CommentUpdateRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CorrectAnswerFilterRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/UnderstoodUpdateRequest.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerIDResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/GPTService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #76
> 응답 형식 변경 사항 리펙토링
>
> refactor: 응답 형식에 맞게 리펙토링(#76)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/UserStatsResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryTest.java
> ex) close #78
> 통계 기능 추가
>
> ex) 이거 서비스가 한줄인데 이거 맞나요..? 쿼리 받을 때 object[]로 리턴 받아서 서비스에서 dto로 변환하는 쪽으로 코드를 짰었는데, 반환에서 오류가 나서 찾아보니 dto 만들어서 jpql에서 new를 통해 쓰면 해당 dto로 데이터를 넣어 주는 기능이 있더라구요
그래서 그걸로 작업했더니 서비스가 한 줄 입니다.. 이거 이렇게 해도 되나요..?
> feat: 히스토리 통계 기능 추가(#78)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerDetailResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
> ex) close #81
> 개별 답변을 조회하는 기능을 추가
>
> feat: 답변 조회 기능 추가(#81)

- inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
- inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
- inpeak/src/main/java/com/blooming/inpeak/member/dto/request/NincknameUpdateRequest.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
close #54 
- 회원 닉네임 변경 기능
- 닉네임은 2자 이상 20자 이하로 설정 가능
> feat: member 닉네임 변경 기능 (#54)

- inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
- inpeak/src/main/java/com/blooming/inpeak/auth/dto/TokenResponse.java
- inpeak/src/main/java/com/blooming/inpeak/auth/service/AuthService.java
- inpeak/src/main/resources/application.yml
close #95 
- Refresh Token으로 새로운 토큰 재발급
> feat: 토큰 재발급 API (#95)

- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
- inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
close #99 
- `회원 탈퇴` 요청시 회원과 관련된 **모든 정보 즉시 삭제**
> feat: member 탈퇴 API (#99)

- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/GPTService.java
> ex) close #101
> 트랜잭션 추가 및 프롬프트 분리
>
> refactor: answer 리펙토링(#101)

- inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
- inpeak/src/main/java/com/blooming/inpeak/member/dto/response/MyPageResponse.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
close #106 
- 마이페이지 조회 API 구현 (`/member/my`)
> feat: 마이페이지 조회 API (#106)

- inpeak/src/main/java/com/blooming/inpeak/common/config/SecurityConfig.java
- inpeak/src/main/java/com/blooming/inpeak/common/config/WebConfig.java
close #111
- cors 설정 spring에서 적용
> chore: cors 설정 spring으로 변경 (#111)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
- inpeak/src/main/java/com/blooming/inpeak/dashborad/controller/InterviewDashboardController.java
- inpeak/src/main/java/com/blooming/inpeak/interview/controller/InterviewController.java
- inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
- inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberInterestController.java
- close #113 
- 모든 API 엔드포인트에 `/api` 경로를 추가합니다.
> 
>
> feat: 모든 API 엔드포인트에 prefix 추가 (#113)

- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerDetailResponse.java
> ex) close #115
> 답변 스킵 시 유저 답변에 모범 답변을 반환하도록 변경
>
> refactor: 답변 스킵 시 모범답변 반환하도록 변경 (#115)

- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorCode.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorHandlingController.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/exception/BadRequestException.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/exception/ConflictException.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/exception/ForbiddenException.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/exception/NotFoundException.java
- inpeak/src/main/java/com/blooming/inpeak/common/error/exception/UnauthorizedException.java
> ex) close #125
> 공통 예외 처리 로직 추가
>
> feat: 공통 예외처리 로직 추가(#125)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
> ex) close #129
> 파라미터 변경에 따라 코드 일부 변경 및 반환값 일부 추가
>
> refactor: 파라미터 변경에 따른 리펙토링(#129)

- inpeak/src/main/java/com/blooming/inpeak/common/utils/LoggingAspect.java
> ex) close #131
> 특정 클래스나 메서드를 로깅에서 제외하는 것이 아니라 200자를 넘는 입력값에 대해 생략하기로 결정
>
> fix: 오디오 파일이 로깅에서 제외되지 않는 문제 해결(#131)

- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
> ex) close #135
> 날짜에 대한 조회에서 분기처리 추가
>
> feat: 날짜 데이터 조회 분기 처리 추가(#135)

- inpeak/src/main/java/com/blooming/inpeak/auth/handler/OAuth2AuthenticationSuccessHandler.java
- inpeak/src/main/java/com/blooming/inpeak/auth/utils/TokenExtractor.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberInterestService.java
close #133 
- 관심분야 선택까지 완료된 회원이라면 로그인 시 메인페이지로 이동
- 관심분야 선택이 안 된 회원이라면 관심분야 설정 페이지로 이동
> feat: OAuth 리다이렉트 URL 처리 방식 개선 (#133)

- inpeak/build.gradle
- inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/common/config/SecurityConfig.java
- inpeak/src/main/java/com/blooming/inpeak/common/config/redis/RedisConfiguration.java
- inpeak/src/main/java/com/blooming/inpeak/dashborad/service/InterviewDashboardService.java
- inpeak/src/main/resources/application.yml
- inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
> ex) close #141이슈번호, #이슈번호
> 느린 성능 api 개선
>
> refactor: api 성능 개선(#141)

- inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
- inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerCreateCommand2.java
- inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerCreateRequest2.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/GPTService.java
> ex) close #147
> 임시 API 추가
>
> feat: AI 답변 임시 API 추가(#147)

- inpeak/src/main/java/com/blooming/inpeak/common/utils/NicknameGenerator.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
close #162 
- 닉네임 생성 로직 개선
- 최초 닉네임 8글자 이하로 생성되도록 수정
> feat: 닉네임 생성 로직 개선 및 최초 닉네임 길이 8글자로 제한 (#162)

- inpeak/src/main/java/com/blooming/inpeak/common/utils/NicknameGenerator.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
PR #162 (닉네임 생성 로직 개선)이 CI 실패 상태로 머지되어 revert 합니다.
> revert: CI 실패로 인한 닉네임 생성 로직 revert (#162)

- inpeak/src/main/java/com/blooming/inpeak/common/utils/NicknameGenerator.java
- inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
- inpeak/src/test/java/com/blooming/inpeak/common/utils/NicknameGeneratorTest.java
close #162 
- 최초 닉네임 생성 로직 개선
- 최초 닉네임 길이 제한
- PR #164 에서 ci 실패로 revert 한 테스트 해결
> feat: 닉네임 생성 로직 개선 및 길이 제한 (#162)

- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerManagerService.java
- inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
> ex) close #166
> 이번 PR에서 작업한 내용을 간략히 설명해주세요. (이미지 첨부 가능)
>
> refactor: 답변 생성 쪽 트랜잭션 분리(#166)
